INSERT INTO ciudad (nombre, idDepartamento) VALUES
                                                ('Aregua', 12),
                                                ('Capiata', 12),
                                                ('Fernando de la Mora', 12),
                                                ('Guarambare', 12),
                                                ('Ita', 12),
                                                ('Itagua', 12),
                                                ('J. Augusto Saldivar', 12),
                                                ('Lambare', 12),
                                                ('Limpio', 12),
                                                ('Luque', 12),
                                                ('Mariano Roque Alonso', 12),
                                                ('Ñemby', 12),
                                                ('Nueva Italia', 12),
                                                ('San Antonio', 12),
                                                ('San Lorenzo', 12),
                                                ('Villa Elisa', 12),
                                                ('Villeta', 12),
                                                ('Ypacarai', 12),
                                                ('Ypane', 12),
                                                ('Asuncion', 1);