INSERT INTO ciudad (nombre, idDepartamento) VALUES
                                                ('Aregua', 48),
                                                ('Capiata', 48),
                                                ('Fernando de la Mora', 48),
                                                ('Guarambare', 48),
                                                ('Ita', 48),
                                                ('Itagua', 48),
                                                ('J. Augusto Saldivar', 48),
                                                ('Lambare', 48),
                                                ('Limpio', 48),
                                                ('Luque', 48),
                                                ('Mariano Roque Alonso', 48),
                                                ('Ñemby', 48),
                                                ('Nueva Italia', 48),
                                                ('San Antonio', 48),
                                                ('San Lorenzo', 48),
                                                ('Villa Elisa', 48),
                                                ('Villeta', 48),
                                                ('Ypacarai', 48),
                                                ('Ypane', 48),
                                                ('Asuncion', 37);