INSERT INTO ciudades(nombre, id_departamento) VALUES('Ciudad del Este', 11);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Domingo Martinez de Irala', 11);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Dr. Juan León Mallorquin', 11);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Juan Emilio O´Leary', 11);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Hernandarias', 11);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Iruña', 11);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Itakyry', 11);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Juan Emilio O´Leary', 11);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Los Cedrales', 11);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Mbaracayú', 11);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Minga Guazú', 11);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Minga Porá', 11);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Ñacunday', 11);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Naranjal', 11);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Presidente Franco', 11);
INSERT INTO ciudades(nombre, id_departamento) VALUES('San Alberto', 11);
INSERT INTO ciudades(nombre, id_departamento) VALUES('San Cristóbal', 11);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Santa Fé del Paraná', 11);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Santa Rita', 11);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Santa Rosa del Monday', 11);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Tavapy', 11);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Yguazú', 11);

INSERT INTO ciudades(nombre, id_departamento) VALUES('Encarnación', 8);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Cambyretá', 8);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Capitán Miranda', 8);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Fram', 8);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Hohenau', 8);
INSERT INTO ciudades(nombre, id_departamento) VALUES('La Paz', 8);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Natalio', 8);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Nueva Alborada', 8);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Obligado', 8);
INSERT INTO ciudades(nombre, id_departamento) VALUES('San Juan del Paraná', 8);
INSERT INTO ciudades(nombre, id_departamento) VALUES('San Pedro del Paraná', 8);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Tomás Romero Pereira', 8);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Trinidad', 8);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Yatytay', 8);

INSERT INTO ciudades(nombre, id_departamento) VALUES('Caacupé', 4);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Altos', 4);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Arroyos y Esteros', 4);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Caraguatay', 4);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Emboscada', 4);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Eusebio Ayala', 4);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Itacurubí de la Cordillera', 4);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Juan de Mena', 4);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Loma Grande', 4);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Mbocayaty del Yhaguy', 4);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Nueva Colombia', 4);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Piribebuy', 4);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Primero de Marzo', 4);
INSERT INTO ciudades(nombre, id_departamento) VALUES('San Bernardino', 4);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Santa Elena', 4);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Tobatí', 4);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Valenzuela', 4);

INSERT INTO ciudades(nombre, id_departamento) VALUES('Villarrica', 5);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Borja', 5);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Colonia Independencia', 5);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Iturbe', 5);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Paso Yobái', 5);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Natalicio Talavera', 5);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Yataity', 5);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Tebicuary', 5);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Félix Pérez Cardozo', 5);
INSERT INTO ciudades(nombre, id_departamento) VALUES('José Fassardi', 5);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Itapé', 5);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Mbocayaty', 5);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Ñumí', 5);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Troche', 5);

INSERT INTO ciudades(nombre, id_departamento) VALUES('Concepción', 2);
INSERT INTO ciudades(nombre, id_departamento) VALUES('San Lázaro', 2);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Loreto', 2);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Horqueta', 2);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Belén', 2);
INSERT INTO ciudades(nombre, id_departamento) VALUES('San Carlos del Apa', 2);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Paso Barreto', 2);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Azotey', 2);
INSERT INTO ciudades(nombre, id_departamento) VALUES('Yby Yaú', 2);